-- 1. Users
CREATE TABLE tblUser (
    UserID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000 INCREMENT BY 1) PRIMARY KEY,
    UserEmail VARCHAR(100) NOT NULL UNIQUE,
    UserPassword CHAR(8) NOT NULL,
    UserFirstName VARCHAR(50) NOT NULL,
    UserLastName VARCHAR(50) NOT NULL,
    UserPhoneNumber CHAR(10) NOT NULL,
    UserBirthDate DATE NOT NULL,
    
    -- Constraints
    CONSTRAINT CK_User_Email CHECK (UserEmail LIKE '_%@_%._%'),
    -- Password: 1 Upper, 5 Lower, 2 Digits. (Postgres LIKE is case-sensitive by default)
    CONSTRAINT CK_User_Password CHECK (UserPassword ~ '^[A-Z][a-z]{5}[0-9]{2}$'),
    CONSTRAINT CK_User_Phone CHECK (UserPhoneNumber ~ '^0[0-9]{9}$'),
    CONSTRAINT CK_User_Age CHECK (EXTRACT(YEAR FROM age(UserBirthDate)) >= 16)
);

-- 2. Sub-types of Users
CREATE TABLE tblArtistUser (
    ArtistUserID INT PRIMARY KEY,
    ArtistPicture VARCHAR(255),
    FOREIGN KEY (ArtistUserID) REFERENCES tblUser(UserID) ON DELETE CASCADE
);

CREATE TABLE tblCriticUser (
    CriticUserID INT PRIMARY KEY,
    FOREIGN KEY (CriticUserID) REFERENCES tblUser(UserID) ON DELETE CASCADE
);

CREATE TABLE tblCuratorUser (
    CuratorUserID INT PRIMARY KEY,
    FOREIGN KEY (CuratorUserID) REFERENCES tblUser(UserID) ON DELETE CASCADE
);

-- 3. Lookup Tables
CREATE TABLE tblTechnic (
    TechnicName VARCHAR(50) PRIMARY KEY
);

CREATE TABLE tblTag (
    TagName VARCHAR(50) PRIMARY KEY
);

CREATE TABLE tblCity (
    CityName VARCHAR(50) PRIMARY KEY
);

-- 4. Creations
CREATE TABLE tblCreation (
    ArtistUserID INT NOT NULL,
    CreationID INT NOT NULL, 
    CreationName VARCHAR(100) NOT NULL,
    CreationDescription TEXT,
    CreationDate DATE NOT NULL,
    TechnicName VARCHAR(50) NOT NULL,
    CreationPrice DECIMAL(10,2) NOT NULL DEFAULT 0 CHECK (CreationPrice >= 0),
    CreationPicture VARCHAR(255),
    CreationVideo VARCHAR(255), 
    Creation3DVisualization VARCHAR(255),
    CreationStatus VARCHAR(15) NOT NULL CHECK (CreationStatus IN ('Available', 'Not Available')),
    CreationIsPhysicalShow BOOLEAN NOT NULL DEFAULT FALSE,
    
    -- Purchase Info
    CriticUserID INT NULL,
    PurchasePrice DECIMAL(10,2) CHECK (PurchasePrice >= 0),
    PurchaseDate DATE,

    PRIMARY KEY (ArtistUserID, CreationID),
    FOREIGN KEY (ArtistUserID) REFERENCES tblArtistUser(ArtistUserID),
    FOREIGN KEY (TechnicName) REFERENCES tblTechnic(TechnicName),
    FOREIGN KEY (CriticUserID) REFERENCES tblCriticUser(CriticUserID)
);

-- 5. Artist Follows Artist
CREATE TABLE tblArtistUserFollow (
    FollowerID INT NOT NULL,
    FollowedID INT NOT NULL,
    ApprovalDate DATE,
    PRIMARY KEY (FollowerID, FollowedID),
    FOREIGN KEY (FollowerID) REFERENCES tblArtistUser(ArtistUserID), 
    FOREIGN KEY (FollowedID) REFERENCES tblArtistUser(ArtistUserID),
    CONSTRAINT CK_Follow_NotSelf CHECK (FollowerID <> FollowedID)
);

-- 6. Tag Associated with Creation
CREATE TABLE tblTAssociatedC (
    TagName VARCHAR(50) NOT NULL,
    ArtistUserID INT NOT NULL,
    CreationID INT NOT NULL,
    MatchToCreation INT NOT NULL CHECK (MatchToCreation BETWEEN 1 AND 5),
    PRIMARY KEY (TagName, ArtistUserID, CreationID),
    FOREIGN KEY (TagName) REFERENCES tblTag(TagName),
    FOREIGN KEY (ArtistUserID, CreationID) REFERENCES tblCreation(ArtistUserID, CreationID) ON DELETE CASCADE
);

-- 7. Galleries
CREATE TABLE tblGallery (
    GalleryID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CuratorUserID INT NOT NULL,
    GalleryName VARCHAR(100) NOT NULL,
    GalleryEmail VARCHAR(100) NOT NULL,
    FOREIGN KEY (CuratorUserID) REFERENCES tblCuratorUser(CuratorUserID) ON DELETE CASCADE,
    CONSTRAINT CK_Gallery_Email CHECK (GalleryEmail LIKE '_%@_%._%')
);

CREATE TABLE tblPhysicalGallery (
    PhysicalGalleryID INT PRIMARY KEY,
    CityName VARCHAR(50) NOT NULL,
    PhysicalGalleryAddress VARCHAR(255) NOT NULL,
    FOREIGN KEY (PhysicalGalleryID) REFERENCES tblGallery(GalleryID) ON DELETE CASCADE,
    FOREIGN KEY (CityName) REFERENCES tblCity(CityName)
);

CREATE TABLE tblDigitalGallery (
    DigitalGalleryID INT PRIMARY KEY,
    -- 3 Required Creations
    ArtistUserID1 INT NOT NULL, CreationID1 INT NOT NULL,
    ArtistUserID2 INT NOT NULL, CreationID2 INT NOT NULL,
    ArtistUserID3 INT NOT NULL, CreationID3 INT NOT NULL,
    
    FOREIGN KEY (DigitalGalleryID) REFERENCES tblGallery(GalleryID) ON DELETE CASCADE,
    FOREIGN KEY (ArtistUserID1, CreationID1) REFERENCES tblCreation(ArtistUserID, CreationID),
    FOREIGN KEY (ArtistUserID2, CreationID2) REFERENCES tblCreation(ArtistUserID, CreationID),
    FOREIGN KEY (ArtistUserID3, CreationID3) REFERENCES tblCreation(ArtistUserID, CreationID),
    
    -- Ensure 3 different creations
    CONSTRAINT CH_Creative_Differences CHECK (
        (ArtistUserID1 <> ArtistUserID2 OR CreationID1 <> CreationID2) AND
        (ArtistUserID1 <> ArtistUserID3 OR CreationID1 <> CreationID3) AND
        (ArtistUserID2 <> ArtistUserID3 OR CreationID2 <> CreationID3)
    )
);

-- 8. Critic Views Digital Gallery
CREATE TABLE tblCViewInDG (
    CriticUserID INT NOT NULL,
    DigitalGalleryID INT NOT NULL,
    Liked BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (CriticUserID, DigitalGalleryID),
    FOREIGN KEY (CriticUserID) REFERENCES tblCriticUser(CriticUserID),
    FOREIGN KEY (DigitalGalleryID) REFERENCES tblDigitalGallery(DigitalGalleryID)
);

-- 9. Exhibitions (Physical)
CREATE TABLE tblExhibition (
    ExhibitionID INT NOT NULL, 
    PhysicalGalleryID INT NOT NULL,
    ExhibitionName VARCHAR(100) NOT NULL,
    ExhibitionDateStart DATE NOT NULL,
    ExhibitionDateEnd DATE NOT NULL,
    ExhibitionSubject VARCHAR(100),
    ExhibitionDescription TEXT,
    ExhibitionStatus VARCHAR(10) CHECK (ExhibitionStatus IN ('Active', 'Inactive')),
    
    PRIMARY KEY (ExhibitionID, PhysicalGalleryID),
    FOREIGN KEY (PhysicalGalleryID) REFERENCES tblPhysicalGallery(PhysicalGalleryID) ON DELETE CASCADE,
    CONSTRAINT CK_Exhibition_Dates CHECK (ExhibitionDateEnd >= ExhibitionDateStart)
);

-- 10. Critic Visits Exhibition
CREATE TABLE tblCVisitedE (
    CriticUserID INT NOT NULL,
    ExhibitionID INT NOT NULL,
    PhysicalGalleryID INT NOT NULL,
    TicketPrice DECIMAL(10,2) NOT NULL CHECK (TicketPrice >= 0),
    VisitDate DATE NOT NULL,
    
    PRIMARY KEY (CriticUserID, ExhibitionID, PhysicalGalleryID),
    FOREIGN KEY (CriticUserID) REFERENCES tblCriticUser(CriticUserID),
    FOREIGN KEY (ExhibitionID, PhysicalGalleryID) REFERENCES tblExhibition(ExhibitionID, PhysicalGalleryID)
);

-- 11. Reviews
CREATE TABLE tblReview (
    ReviewID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CriticUserID INT NOT NULL,
    ExhibitionID INT NOT NULL,
    PhysicalGalleryID INT NOT NULL,
    ReviewDegree INT CHECK (ReviewDegree BETWEEN 1 AND 5),
    ReviewText TEXT,
    
    UNIQUE (CriticUserID, ExhibitionID, PhysicalGalleryID), 
    FOREIGN KEY (CriticUserID, ExhibitionID, PhysicalGalleryID) 
        REFERENCES tblCVisitedE(CriticUserID, ExhibitionID, PhysicalGalleryID) ON DELETE CASCADE
);

-- 12. Responses to Reviews
CREATE TABLE tblResponse (
    ResponseID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ReviewID INT NOT NULL,
    ResponseText TEXT NOT NULL,
    ResponseDateTime TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ReviewID) REFERENCES tblReview(ReviewID) ON DELETE CASCADE
);