-- Show all tables:
select * from tblUser;
select * from tblArtistUser;
select * from tblCriticUser;
select * from tblCuratorUser;
select * from tblCity;
select * from tblTechnic;
select * from tblTag;
select * from tblGallery;
select * from tblPhysicalGallery;
select * from tblDigitalGallery;
select * from tblCreation;
select * from tblArtistUserFollow;
select * from tblTAssociatedC;
select * from tblExhibition;
select * from tblCVisitedE;
select * from tblReview;
select * from tblResponse;